alias ls 'ls -G --color'
alias lsa 'ls -a'
alias h 'history | head -n 20'
alias c 'clear'
alias reload 'source ~/.config/fish/config.fish ; echo Bash config reloaded'
alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias cd6 'cd ~/code/6.Semester/'
alias cdaoc 'cd ~/code/AdventOfCode/'

alias gac 'git_ac'
alias gp 'git pull'

alias delete_junk_files 'find . -name "*:Zone.Identifier" -type f -delete'
