alias ls 'ls -G --color'
alias lsa 'ls -a'
alias h 'history | head -n 20'
alias c 'clear'
alias reload 'source ~/.config/fish/config.fish ; echo Bash config reloaded'
alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias cd7 'cd ~/code/7.Semester/'
alias wao 'cd ~/code/7.Semester/WAO/'
alias bac 'cd ~/code/7.Semester/BAC/SW7BAC/'
alias bacd 'cd ~/code/7.Semester/BAC/SW7BAC_docs/'
alias aoc 'code ~/code/AdventOfCode/'
alias waoc 'code ~/code/7.Semester/WAO/'

alias config 'cd ~/.config/fish/'

alias gac 'git_ac'
alias gp 'git pull'
alias lg 'lazygit'

alias delete_junk_files 'find . -name "*:Zone.Identifier" -type f -delete'
